version: "1"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '${APP_NAME}-webserver'
    restart: 'always'
    ports:
      - "8888:80"
      - "4444:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT}./wwww:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${LOG_DIR}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: '${APP_NAME}-mysql'
    restart: 'always'
    ports:
      - "3333:3306"
    volumes: 
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: gamo2
      # MYSQL_USER: gamo2
      # MYSQL_PASSWORD: gamo2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${APP_NAME}-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '9999:80'
    volumes: 
      - /sessions
  redis:
    container_name: '${APP_NAME}-redis'
    image: redis:latest
    ports:
      - "6666:6379"